config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  namespace :post do
    resources :comments
  end
  get 'news', to: 'news#main'
  devise_for :users, :controllers => {registrations: 'registrations'}
  get 'users/:id' => 'users#show', as: :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  resource :connections, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/connection.rb
class Connection < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  scope :following, -> (followers) { where user_id: followers }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many :active_connections, class_name:"Connection", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_connections, source: :followed

  has_many :passive_connections, class_name:"Connection", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_connections, source: :follower

  def follow(user)
    active_connections.create(followed_id: user.id)
  end
  def unfollow(user)
    active_connections.find_by(followed_id: user.id).destroy
  end
  def following?(user)
    following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET posts/1/comments
  def index
    @comments = @post.comments
  end

  # GET posts/1/comments/new
  def new
    @comment = @post.comments.build
  end

  # POST posts/1/comments
  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end
    redirect_to post_path(@post)
  end

  # DELETE posts/1/comments/1
  def destroy
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params
        .require(:comment)
        .permit(:comment)
        .merge(post_id: params[:post_id])
    end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_user

    def create
        current_user.follow(@user)
        redirect_to @user
    end

    def destroy
        current_user.unfollow(@user)
        redirect_to @user
    end

    private
    
    def find_user
        @user = User.find(params[:user_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def homepage
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def main
        client = Client.new
        @headlines = client.headlines
        @updates = client.coin_updates
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @user_posts = Post.where(user_id: current_user.id).order("created_at DESC")
    @following_posts = Post.where(:user_id => [current_user.following]).order("created_at DESC")
    @posts = (@user_posts + @following_posts)
    @post = current_user.posts.build
    @user = User.all
    @user_follow = @user.where.not(:id => [current_user.following])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @user = User.where(id: @post.user_id)
    @comments = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :description, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation, :current_password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    @posts_count = Post.where(user_id: @user.id).count
    @following_count = User.where(:id => [@user.following]).count
    @follower_count = User.where(:id => [@user.followers]).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comment.comment? %>
    <div class="card" style="width: 100%;">
    <div class="card-body">
        <h5 class="card-title h3"><%= comment.user.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted h4">@<%= comment.user.username %></h6>
        <p class="card-text h1"><%= comment.comment %></p>
        <% if comment.user.id == current_user.id %>
            <%= link_to 'Delete comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-1" %>
        <% end %>
    </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<div style="width: 100%">
  <form class="d-flex" action="<%= post_comments_path(post) %>" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <textarea name="comment[comment]" class="form-control ml-1 shadow-none textarea"></textarea>
    <input type="submit" value="Submit" class="btn btn-primary btn-lg">
  </form>
</div>

app/views/home/homepage.html.erb
<body class="bg-dark text-white">
<% if user_signed_in? %>
    <body id="page-top justify-content-center">
        <header class="masthead d-flex align-middle align-items-center">
            <div class="container mt-5 px-10 px-lg-10 text-center">
                <div class="mt-5">
                    <h1 class="mb-1 mt-5">Tokespace</h1>
                    <br>
                    <h3 class="mb-5"><em>Welcome to Tokespace! A social media app for crypto and blockchain enthusiasts!</em></h3>
                </div>
            </div>
        </header>
    </body>    
<%else%>
    <body id="page-top justify-content-center">
        <header class="masthead d-flex align-middle align-items-center">
            <div class="container mt-5 px-10 px-lg-10 text-center">
                <div class="mt-5">
                    <h1 class="mb-1 mt-5">Tokespace</h1>
                    <br>
                    <h3 class="mb-5"><em>Welcome to Tokespace! A social media app for crypto and blockchain enthusiasts!</em></h3>
                    <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
        </header>
    </body>
<%end%>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokespace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary sticky-top">
        <div class="container">
            <a class="navbar-brand py-2"><%= link_to 'Tokespace', root_path, class: "btn btn-outline-light", style: "font-size: large" %></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <% if user_signed_in? %>
                <ul class="navbar-nav ms-auto py-0">
                    <div class="d-flex col mt-1 px-2">
                      <li class="nav-item px-2"><%= link_to 'Posts', posts_path, class: 'btn btn-outline-light', style: "font-size: large"%></li>
                      <li class="nav-item px-2"><%= link_to 'Crypto News', news_path, class: 'btn btn-outline-light', style: "font-size: large" %></li>
                    </div>
                    <li class="nav-item dropdown d-flex flex-row-reverse">
                        <a class="nav-link dropdown-toggle py-0 mb-0 pb-0" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><%= link_to current_user.username, user_path(current_user), class: 'nav-link text-white mb-0 py-3 h3' %></a>
                        <ul class="dropdown-menu dropdown-menu-end py-5 justify-center text-center" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#"><%= link_to 'Edit account', edit_user_registration_path, class: 'text-dark h3 py-0' %></a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-danger h3 py-0' %></a></li>
                        </ul>
                    </li>
                </ul>
              <% end %>
            </div>
        </div>
    </nav>

    <% if flash[:notice]%>
        <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert]%>
        <p class="alert"><%= alert %></p>
    <% end %>
      
    <%= yield %>
  </body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

app/views/news/main.html.erb

<%# scrollbar styling %>
<style>
    /* width */
    ::-webkit-scrollbar {
    width: 6px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
    background: #f1f1f1; 
    }
    
    /* Handle */
    ::-webkit-scrollbar-thumb {
    background: #888; 
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
    background: #555; 
    }
</style>

<body class="bg-dark" style='scrollbar-color: dark;'>
    <div class="container-fluid row d-flex justify-content-center">
        <h1 class="text-center text-white">Latest Crypto and Blockchain news</h1>
        <br>
        <br>
        <br>
            <div class="container">
                <div class="col d-flex justify-content-center">
                    <div style="max-height: 800px; overflow-y: auto;  scrollbar-width: thin; scrollbar-color: black gray;">
                        <% @headlines['results'].each do |headline|%>
                            <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"><%= headline['title'] %></h5>
                                <p class="card-text">Published at <%= headline['published_at'].tr("T Z", " ") %>UTC</p>
                                <a href="<%= headline['url']%>" target ="_blank" class="btn btn-secondary">Click here for more information</a>
                            </div>
                            </div>
                        <% end %>
                    </div>
                    <div class="d-inline-block position-sticky" style="max-height: 800px; overflow-y: auto; scrollbar-color: dark;">
                        <% @updates.each do |updates|%>
                        <div class="card bg-dark" style="width: 18rem;">
                            <div class="card-body text-muted">
                                <h5 class="card-title text-white"><%= updates['symbol'].upcase %></h5>
                                <h6 class="card-subtitle mb-2 text-light">Current Price: $<%= updates['current_price'] %></h6>
                                <% if updates['price_change_percentage_24h'] > 0%>
                                    Last 24hrs:<p class="card-text text-success"> <%= updates['price_change_percentage_24h'] %>%</p>
                                <% elsif updates['price_change_percentage_24h'] < 0 %>
                                    Last 24hrs:<p class="card-text text-danger"> <%= updates['price_change_percentage_24h'] %>%</p>
                                <%end%>
                            </div> 
                        </div>
                        <%end%> 
                    </div>
                </div>
            </div>
    </div>
</body>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <div class="d-flex row justify-content-center text-white h3">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="d-flex row form-inputs justify-content-center">
      <%= f.input :description, label: 'Post',placeholder: 'Post Something' %>
    </div>

    <div class="d-flex form-actions mb-5 justify-content-center">
      <%= f.button :submit, class:'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<body class = "bg-dark">
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card px-5 py-5 justify-content-center" id="form1">
                    <h1>Editing Post</h1>

                    <%= render 'form', post: @post %>
                    <%= link_to 'Back', posts_path %>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<body class="bg-dark" style='scrollbar-color: dark;'>
<div class="d-flex justify-content-center">
  <div class="container d-flex row justify-content-center px-5">
      <div class="d-flex col justify-content-between">
      <div class="card p-3" style="max-height: 18rem;">
          <div class="d-flex align-items-center">
              <div class="image"> <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" class="rounded-circle" width="155"> </div>
              <div class="ml-3 w-100">
                  <h4 class="mb-0 mt-0 h3"><%= current_user.name %></h4> <span class="h3">@<%= current_user.username %></span>
                  <div>
                  </div>
                  <div class="button mt-2 d-flex flex-row align-items-center">
                    <%= link_to 'View My Profile', user_path(current_user), class:"btn btn-sm btn-primary w-100 ml-2"%>
                  </div>
              </div>
          </div>
      </div>    
        <div class ="align-self-center w-75 px-5">
            <%= render 'form', post: @post %>
              <% @posts.each do |post| %>
                <div class="card text-center">
                  <div class="card-header h5">
                    <%= link_to post.user.username, user_path(post.user), class:"text-dark"%>
                  </div>
                  <div class="card-body">
                    <h2 class="card-title"><%= post.description %></h2>
                    <div class="d-flex col justify-content-center">
                    <%= link_to "View Comments", post, class: "btn btn-secondary mx-1" %>
                      <% if post.user_id == current_user.id %>
                        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-secondary mx-1" %>
                        <%= link_to 'Delete Post', post,method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-1" %>
                      <% end %>
                    </div>        
                  </div>
                  <div class="card-footer text-muted">
                    <%= post.created_at%>    
                  </div>
                </div>
                <hr/>
              <% end %>
        </div>
          <div class="justify-content-center">
            <h3 class='text-white text-center'>Get to know more people!</h3>
              <% @user_follow.each do |user|%>
                  <% if user.id != current_user.id %>
                    <div class="card p-3" style="max-height: 18rem;">
                        <div class="d-flex align-items-center">
                            <div class="image"> <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" class="rounded-circle" width="155"> </div>
                            <div class="ml-3 w-100">
                                <h4 class="mb-0 mt-0"><%= user.name %></h4> <span><%= user.username %></span>
                                <div>
                                </div>
                                <div class="button mt-2 d-flex flex-row align-items-center">
                                  <%= link_to 'View Profile', user_path(user), class:"btn btn-sm btn-primary w-100 ml-2"%>
                                </div>
                            </div>
                        </div>
                    </div>
                    <%end%>
              <%end%>
            </div>
    </div>
  </div>
  </div>
</body>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<body class="bg-dark" style='scrollbar-color: dark;'>
  <div class="container-fluid row d-flex justify-content-center">
    <div class="container">
      <div class="col d-flex justify-content-center">
          <div style="width: 100%;">
              <div class="container mt-5 mb-5">
                  <div class="d-flex justify-content-center row">
                      <div class="d-flex flex-column col-md-8">
                        <%= link_to 'Back', posts_path %>
                          <div class="d-flex flex-row align-items-center text-left comment-top p-2 bg-white border-bottom px-4">
                              <div class="profile-image"><img class="rounded-circle" src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" width="70"></div>
                              <div class="d-flex flex-column-reverse flex-grow-0 align-items-center votings ml-1"><i class="fa fa-sort-up fa-2x hit-voting"></i><i class="fa fa-sort-down fa-2x hit-voting"></i></div>
                              <div class="d-flex flex-column ml-3">
                      
                                  <div class="d-flex flex-row post-title">
                                      <h3><%= @post.description %></h3><span class="ml-2"></span>
                                  </div>
                                  <div class="d-flex flex-row align-items-center align-content-center post-title"><span class="mr-2 comments px-3">(<%= @post.comments.count %>)comments&nbsp;</span><span class="mr-2 dot"></span><span class="px-4"><%= @post.created_at %></span></div>
                                  <% if user_signed_in? && @post.user_id == current_user.id %>
                                    <%= link_to 'Edit Post', edit_post_path(@post) %>
                                  <% end %>
                              </div>
                          </div>
                          <div class="comment-bottom bg-white p-2 px-4">
                              <div class="profile-image d-flex col">
                                <div class="d-flex row">
                                <span class= "px-2 h4">Commenting as: @<%= current_user.username %></span>
                                <%= render partial: 'comments/form', locals: {post: @post} %></div>
                                </div>
                              </div>
                              <%= render @post.comments %>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<body class="bg-dark">
<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto">
        <!-- Profile widget -->
        <div class="bg-secondary shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3 py-5"><img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="..." width="130" class="rounded-circle mb-2 img-thumbnail">
                        <% if user_signed_in? && @user != current_user %>
                            <% if current_user.following?(@user) %>
                                <%= button_to "Unfollow", connections_path(user_id: @user.id), method: :delete, class: "btn btn-outline-primary btn-sm btn-block bg-primary text-white"%>
                            <% else %>
                                <%= button_to "Follow", connections_path(user_id: @user.id), class: "btn btn-outline-primary btn-sm btn-block bg-primary text-white"%>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="media-body mb-3 text-white">
                        <h4 class="display-1 mt-0 mb-0"><%= @user.name%></h4>
                        <p class="display-5 mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>@<%= @user.username%></p>
                    </div>
                </div>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block"><%= @posts_count %></h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Posts</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block"><%= @follower_count %></h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block"><%= @following_count %></h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
                    </li>
                </ul>
            </div>
            <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Posts</h5><a href="#" class="btn btn-link text-muted"></a>
                </div>
                    <%@posts.each do |post|%>
                        <div class="card" style="width: 100%;">
                            <div class="card-body">
                                <h5 class="card-title"><%= post.user.name %></h5>
                                <h6 class="card-subtitle mb-2 text-muted">@<%= post.user.username %></h6>
                                <p class="card-text display-5"><%= post.description %></p>
                                <%= link_to "View Comments", post, class: "btn btn-secondary mx-1" %>
                                <% if post.user_id == current_user.id %>
                                    <%= link_to 'Edit', edit_post_path(post), class: "btn btn-secondary mx-1" %>
                                    <%= link_to 'Delete Post', post,method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-1" %>
                                <% end %>
                            </div>
                        </div>
                    <%end%>
            </div>
        </div>
    </div>
</div>
</body>